name: Crawl PSJP (left half)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 600
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: |
          pip install beautifulsoup4 matplotlib
          sudo apt-get install -y jq fonts-motoya-l-maruberi
      - name: record update time
        run: TZ="JST-9" date +"%Y年%-m月%-d日%-H時" > data/update.txt
      - name: crawl psjp data
        run: python python/crawl-psjp-data.py --min 801 --max 1500 | jq -s "unique_by(.id)" > data/data-2.json
      - name: git push
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add data/data-2.json
          git commit -m "update psjp data-2"
          git push origin main
