name: Crawl PSJP everyday
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install package
        run: |
          pip install beautifulsoup4
          sudo apt-get install -y jq
      - name: crawl-psjp-data
        run: python crawl-psjp-data.py | jq -s . > data/data.json
      - name: git push
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add data/data.json
          git commit -m "update data.json"
          git push origin main
