name: Crawl PSJP
on:
  workflow_dispatch:
  schedule:
    # 日本時間で日付が変わってすぐに実行する
    - cron: '10 15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: |
          pip install beautifulsoup4 matplotlib
          sudo apt-get install -y jq fonts-motoya-l-maruberi
      - name: get psjp data
        run: ./script/get-data.sh
      - name: cut psjp data
        run: python script/cut-data.py
      - name: make graph
        run: |
          python script/graph/problem.py
          python script/graph/date.py
          python script/graph/first.py
          python script/graph/span.py
          python script/graph/latest.py
      - name: git push
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add data/* graph/*
          git commit -m "update psjp data"
          git push origin main
