name: Update Puzzle Square Stat
on:
  workflow_dispatch:
    inputs:
      delete:
        description: "データを削除して取り直す"
        required: true
        default: false
        type: boolean
  schedule:
    # 日本時間で日付が変わってすぐに実行する
    - cron: '1 15 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: |
          pip install beautifulsoup4 matplotlib
          sudo apt-get install -y jq fonts-motoya-l-maruberi
      - name: delete data (if you want)
        if: ${{ inputs.delete }}
        run: rm data/data.json
      - name: get psjp data
        run: ./script/get-data.sh
      - name: cut psjp data
        run: python script/cut-data.py
      - name: make graph
        run: |
          python script/graph/activity.py
          python script/graph/date.py
          python script/graph/difficulty.py
          python script/graph/favor.py
          python script/graph/first.py
          python script/graph/problem.py
          python script/graph/solver.py
          python script/graph/span.py
          python script/graph/top.py
      - name: git push
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add data/* graph/*
          DATE=$(cat data/update.txt)
          git commit -m "update psjp data $DATE"
          git push origin main
